[executor.default]
type = "Local"

[executor.slurm_base]
type = "Slurm"
staging_mode = "Copy"
cpus = 4
memory = { type = "per_cpu", amount = 8192 }
tasks = 1
nodes = 1
time = { days = 1, hours = 2 }
account = "my-account-id"
mail_user = "myemail@gmail.com"
mail_type = ["NONE", "TIME_LIMIT_50"]
additional_options = [
    ["qos", "high"]
]

[executor.slurm2]
inherit = "slurm_base"
tasks = 2
cpus = 10

[args]
init_msg = "Hello, world!"

[inputs]
alphafold_inputs = ["data/input1.pdb", "data/input2.pdb"]
