# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib
import typing
from enum import Enum

class LocalExecutor:
    def new(self) -> LocalExecutor: ...
    def with_staging_mode(self, mode:StagingMode) -> None: ...
    def with_error_handling(self, y:builtins.bool) -> None: ...
    def exe(self, process:Process) -> builtins.list[pathlib.Path]: ...

class Process:
    r"""
    Process struct
    """
    def __init__(self, name:builtins.str, script:builtins.str, inputs:typing.Mapping[builtins.str, builtins.str | os.PathLike | pathlib.Path], outputs:typing.Mapping[builtins.str, builtins.str | os.PathLike | pathlib.Path], args:typing.Mapping[builtins.str, builtins.str]) -> Process:
        r"""
        Constructor
        """

class StagingMode(Enum):
    r"""
    Staging mode
    """
    Copy = ...
    Symlink = ...
    None = ...

