[package]
name = "maestro-cli"
version = "0.1.3"
edition = "2024"

[[bin]]
name = "maestro"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
session_gen = { workspace = true }
