use std::{env, io, path::PathBuf};

use rand::{Rng, distr::Uniform, seq::IndexedRandom};

pub(crate) fn generate_session_id() -> String {
    let mut rng = rand::rng();
    let selected_adj = ADJECTIVES
        .choose(&mut rng)
        .expect("ADJECTIVES should not be empty for session ID selection!");
    let selected_animal = ANIMALS
        .choose(&mut rng)
        .expect("ANIMALS should not be empty for session ID selection!");
    format!("{}-{}", selected_adj, selected_animal)
}

pub(crate) fn generate_hash() -> String {
    let rng = rand::rng();
    let letter_sample =
        Uniform::new_inclusive('a', 'z').expect("Uniform character sampling should not fail!");
    rng.sample_iter(letter_sample).take(8).collect()
}

pub(crate) fn gwd() -> Result<PathBuf, io::Error> {
    const FINALFLOW_DIRNAME: &str = "finalflow_work";
    match env::var("FINALFLOW_WORK") {
        Ok(v) => Ok(PathBuf::from(v).join(FINALFLOW_DIRNAME)),
        Err(_) => env::current_dir().map(|p| p.join(FINALFLOW_DIRNAME)),
    }
}

const ADJECTIVES: [&str; 100] = [
    "joyful",
    "grateful",
    "thrilled",
    "amused",
    "angry",
    "hopeful",
    "appreciative",
    "cheerful",
    "inspired",
    "sad",
    "affectionate",
    "proud",
    "enthusiastic",
    "elated",
    "content",
    "calm",
    "peaceful",
    "relaxed",
    "worried",
    "serene",
    "blissful",
    "exuberant",
    "radiant",
    "upbeat",
    "anxious",
    "cheery",
    "lively",
    "sunny",
    "bubbly",
    "vibrant",
    "delighted",
    "pleased",
    "frustrated",
    "mellow",
    "comical",
    "confident",
    "gracious",
    "accomplished",
    "satisfied",
    "stressed",
    "fulfilled",
    "happy",
    "harmonious",
    "sociable",
    "loving",
    "caring",
    "lonely",
    "compassionate",
    "empathetic",
    "friendly",
    "welcoming",
    "ecstatic",
    "jovial",
    "grumpy",
    "jubilant",
    "merry",
    "gleeful",
    "lighthearted",
    "carefree",
    "exhausted",
    "playful",
    "whimsical",
    "ambitious",
    "motivated",
    "determined",
    "focused",
    "irritated",
    "energized",
    "invigorated",
    "refreshed",
    "rejuvenated",
    "optimistic",
    "overwhelmed",
    "trustful",
    "bold",
    "courageous",
    "fearless",
    "animated",
    "disappointed",
    "spirited",
    "witty",
    "curious",
    "fascinated",
    "amazed",
    "gloomy",
    "astonished",
    "awed",
    "buoyant",
    "sentimental",
    "nostalgic",
    "bitter",
    "reflective",
    "thoughtful",
    "betrayed",
    "cynical",
    "miserable",
    "confused",
    "crushed",
    "jealous",
    "annoyed",
];

const ANIMALS: [&str; 100] = [
    "dog",
    "cow",
    "cat",
    "horse",
    "donkey",
    "tiger",
    "lion",
    "panther",
    "leopard",
    "cheetah",
    "bear",
    "elephant",
    "turtle",
    "tortoise",
    "crocodile",
    "rabbit",
    "porcupine",
    "hare",
    "hen",
    "pigeon",
    "crow",
    "fish",
    "dolphin",
    "frog",
    "whale",
    "alligator",
    "eagle",
    "ostrich",
    "fox",
    "goat",
    "jackal",
    "armadillo",
    "eel",
    "goose",
    "wolf",
    "gorilla",
    "chimpanzee",
    "monkey",
    "beaver",
    "orangutan",
    "antelope",
    "bat",
    "badger",
    "giraffe",
    "hamster",
    "cobra",
    "camel",
    "hawk",
    "deer",
    "chameleon",
    "hippopotamus",
    "jaguar",
    "lizard",
    "koala",
    "kangaroo",
    "iguana",
    "llama",
    "jellyfish",
    "rhinoceros",
    "hedgehog",
    "zebra",
    "possum",
    "wombat",
    "bison",
    "bull",
    "buffalo",
    "sheep",
    "meerkat",
    "mouse",
    "otter",
    "sloth",
    "owl",
    "vulture",
    "flamingo",
    "racoon",
    "mole",
    "duck",
    "swan",
    "lynx",
    "elk",
    "boar",
    "lemur",
    "mule",
    "baboon",
    "mammoth",
    "snake",
    "peacock",
    "squirrel",
    "crab",
    "panda",
    "shark",
    "chinchilla",
    "pig",
    "penguin",
    "seal",
    "spider",
    "ant",
    "bee",
    "fly",
    "parrot",
];
